### ISSUE TITLE
Consider the same API as draftjs-plugins

### ISSUE THREAD

**Issue by okonet** [SamyPesse/draft-js-prism#1] opened 2016-05-25 15:40 UTC
There is a cool project https://github.com/draft-js-plugins/draft-js-plugins that has a very nice plugin API for draft-js. I really like how you can just define an array of plugins you want to use:

``` jsx
import React, { Component } from 'react';
import Editor from 'draft-js-plugins-editor';
import createHashtagPlugin from 'draft-js-hashtag-plugin';
import createLinkifyPlugin from 'draft-js-linkify-plugin';
import { EditorState } from 'draft-js';

const hashtagPlugin = createHashtagPlugin();
const linkifyPlugin = createLinkifyPlugin();

const plugins = [
  hashtagPlugin,
  linkifyPlugin,
];

export default class UnicornEditor extends Component {

  state = {
    editorState: EditorState.createEmpty(),
  };

  onChange = (editorState) => {
    this.setState({
      editorState,
    });
  };

  render() {
    return (
      <Editor
        editorState={this.state.editorState}
        onChange={this.onChange}
        plugins={plugins}
        ref="editor"
      />
    );
  }
}
```

Would you consider adapting this API?

**Comment by okonet** [comment] 2016-05-25 15:40
cc @nikgraf

**Comment by SamyPesse** [comment] 2016-05-27 10:23
I prefer to keep a low level API, but we can easily also expose a plugin for `draftjs-plugins` (in this plugin or in another one).

But I think one of the main advantage of Draft is that its API can be low level and really customisable, and APIs like the  `draftjs-plugins` one should stay an abstraction on top of that instead of being the main convention.

**Comment by okonet** [comment] 2016-05-27 11:19
I'm wondering if you checked out the `draftjs-plugins` API since this is exactly what they are trying to achieve: a low-level but very developer-friendly API to add several plugins to DraftJS instance without using tons of HoCs.

**Comment by nikgraf** [comment] 2016-05-27 17:03
@SamyPesse cool tool. Is there a way to get out a decorator that has a Strategy and Component to be used within the `CompositeDecorator ` https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#compositedecorator provided by DraftJS? If yes, creating a plugin (which would be really cool) wouldn't take any member for the plugins team more than an hour or two 😄

@okonet thx for mentioning me

**Comment by SamyPesse** [comment] 2016-05-30 07:54
@nikgraf  `CompositeDecorator` are a subset of that i's possible with decorators an Draft, the problem is that `CompositeDecorator` limits the component/props to be global to the decorator.

In the case of the prism decorator, we need different props according to the type of tokens. So basically, it's not possible to build the prism highlighting as a `CompositeDecorator`.

But I've build [draftjs-multidecorators](https://github.com/SamyPesse/draftjs-multidecorators) to accept multiple decorators (composite or not) and return one.

Do `draftjs-plugins` only accept composite decorator for now?

**Comment by nikgraf** [comment] 2016-05-30 22:05
@SamyPesse yes, at least for now. https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L55-L59

I didn't really considered creating something else until there is a valid use-case (I didn't imagine there would be soon). draftjs-prism now is 😄 

Might be interesting to use the multidecorators in the core. Are there any downsides using it that you have encountered?

**Comment by mxstbr** [comment] 2017-09-22 19:43
I've wrapped this decorator to be compatible with `draft-js-plugins` in [`draft-js-prism-plugin`](https://github.com/withspectrum/draft-js-prism-plugin) and that works perfectly fine, so I'll close this issue!

**Closed by mxstbr** 2017-09-22 19:43 UTC
Labels: question
